### ISSUE TITLE
can you added http://ouo.io?

### ISSUE THREAD

**Issue by leech24** [HeroCC/yourls-conditional-urlads#2]
can you added http://ouo.io?

i try in my web adf.ly bot doent work
plz make some update

my web is alsi.ga

**Comment by HeroCC** [comment]
I just pushed a commit that adds [http://ouo.io/](http://ouo.io/ref/0IqYvHOo) support, I'm not at a place where I can test it though. If you have any troubles let me know and I'll do my best to fix them.
