### ISSUE TITLE
Links redirect to yourls home

### ISSUE THREAD

**Issue by ghost** [HeroCC/yourls-conditional-urlads#3]
The plugin seems to be working except when i go to mywebsite.com/a/foo, I go through adfly but I just get redirected to mywebsite.com instead of where mywebsite.com/foo is supposed to redirect.

If I hover on the skip ad button it shows mywebsite.com so it must be a problem with the plugin config?

**Comment by 8MiYile** [comment]
~~This problem has not been solved until now?~~
is solved
https://github.com/8Mi-Tech/yourls-conditional-urlads
Update Note: https://github.com/8Mi-Tech/yourls-conditional-urlads/issues/1

**Comment by HeroCC** [comment]
Fixed in #4
