### ISSUE TITLE
Do I need to give you back my branch?

### ISSUE THREAD

**Issue by 8MiYile** [HeroCC/yourls-conditional-urlads#5]
Do I need to give you back my branch?
you can look update note
https://github.com/8Mi-Tech/yourls-conditional-urlads/issues/1

**Comment by HeroCC** [comment]
Up to you! If you'd like to contribute, feel free to make a new pull requests for each change / feature you'd like to add. 

I unfortunately don't speak Chinese so I'm not comfortable maintaining that README in my repo. Splitting the `user-settings.php` into another file is a good idea so I'd be happy to help work on that, same with swapping the `if`s to switch statements.

**Comment by 8MiYile** [comment]
I'll do my best.
https://github.com/HeroCC/yourls-conditional-urlads/pull/6
if merged
pls close this issue

**Comment by 8MiYile** [comment]
https://github.com/HeroCC/yourls-conditional-urlads/issues/5
